/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 * @Modified by    : Nagaraju Lakkaraju
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 * Bare-metal STM32F103 “Bluepill” program where:
 * PA0 triggers an EXTI interrupt (button press).
 * PC13 LED toggles in the interrupt.
 * Just register-level programming.
 */

#include <stdint.h>
#include "console.h"
#include "exti.h"
#include "adc.h"

int main(void)
{
	uint32_t adc_mV;

	EXTI_PA0_Init();
	PC13_LED_Init();

    /* Initialize UART1 */
    uart1_init();
    printf("%s(): STM32F103(Bluepill) External Interrupt(@PA0) - LED Test !!! \r\n", __func__);

    ADC1_Init();

    adc_mV = ADC1_Read();
    printf("%s(): ADC Voltage :%lu mV\r\n", __func__, adc_mV);

    while(1) {
        // Main loop does nothing, LED toggled in ISR
    }
}


